services:
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./tmbo/:/var/www/html
  php:
    build: ./web/
    container_name: php
    expose:
      - 9000
    volumes:
      - ./tmbo/:/var/www/html
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  # web:
  #   image: php:7.2-apache
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./web:/var/www/html
  #   depends_on:
  #     - mysql
