services:
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./web/src/:/var/www/html
  php:
    build: ./web/
    container_name: php
    expose:
      - 9000
    volumes:
      - ./web/src/:/var/www/html
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: shortbus
      MYSQL_DATABASE: tmbo
      MYSQL_USER: tmbo
      MYSQL_PASSWORD: shortbus
    ports:
      - "3306:3306"
    volumes:
      - ./temp/mysql:/var/lib/mysql
      - ./data/db-setup:/docker-entrypoint-initdb.d
  # web:
  #   image: php:7.2-apache
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./web:/var/www/html
  #   depends_on:
  #     - mysql
